export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAIL = "FETCH_INGREDIENTS_FAIL";

export const LOADING = "LOADING";

export const ORDER_SUBMIT_SUCCESS = "ORDER_SUBMIT_SUCCESS";
export const ORDER_SUBMIT_FAIL = "ORDER_SUBMIT_FAIL";
export const ORDER_SUBMIT_START = "ORDER_SUBMIT_START";
export const ORDER_INIT = "ORDER_INIT";

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_REDIRECT_AUTH_PATH = 'SET_REDIRECT_AUTH_PATH'; 