export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const LOADING = "LOADING";

export const ORDER_SUBMIT_SUCCESS = "ORDER_SUBMIT_SUCCESS";
export const ORDER_SUBMIT_FAILED = "ORDER_SUBMIT_FAILED";
export const ORDER_SUBMIT_STARTED = "ORDER_SUBMIT_STARTED";

